<?php
include_once "Point2D.php";
class Point3D extends Point2D
{
public $z;
public function __construct($x, $y,$z)
{
    parent::__construct($x, $y);
    $this->z = $z;
}

    /**
     * @return mixed
     */
    public function getZ()
    {
        return $this->z;
    }

    /**
     * @param mixed $z
     */
    public function setZ($z): void
    {
        $this->z = $z;
    }
    public function getXYZ()
    {

    }
    public function setXY($x, $y,$z)
    {
        parent::setXY($x, $y); // TODO: Change the autogenerated stub
        $this->z = $z;
    }
    public function toString(): string
    {
        return " Toa do X la : " . $this->x . " , " . " toa do Y la : " . $this->y . " va toa do Z la : " . $this->z;
    }
}